[package]
name = "mm_token_rs"
version = "0.1.0"
edition = "2021"
default-run = "sell_bot"

[dependencies]
mm_token_utils = { workspace = true }
mm_token_toolkit = { workspace = true }
provider_utils = { workspace = true }

anyhow = { workspace = true }
chrono = { workspace = true }
dotenv = { workspace = true }
ethers = { workspace = true }
fern = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
rust_decimal = { workspace = true }
bigdecimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
rocket = { workspace = true }
rocket_codegen = { workspace = true }
teloxide = { workspace = true }
lettre = { workspace = true }
cached = { workspace = true }
